# This Python file uses the following encoding: utf-8

import os
import sys
sys.path.append('..')
from unicodeMagic import UnicodeReader, UnicodeWriter
from dictUtils import MyDict
from nameMap import nameMap
from unidecode import unidecode
from folderUtils import MyFolder
from bs4 import BeautifulSoup


dataPath = os.path.abspath("/Users/bogdanv/Downloads/dblp/ht/db/conf")
citesPath = os.path.abspath("/Users/bogdanv/Downloads/dblp/publ")
outPath = os.path.abspath("/Users/bogdanv/icse-harmful/msrdata")

conferences = ['icse', 'icsm', 'wcre', 'csmr', 'msr', 'gpce', 'fase', 'iwpc', 'sigsoft', 'scam', 'kbse']
conferences = ['msr']


for conference in conferences:
    
    print conference
    
    f = open(os.path.join(outPath, 'selection', '%s_papers.csv' % conference), 'rb')
    reader = UnicodeReader(f)
    
    g = open(os.path.join(outPath, 'research-papers', '%s.csv' % conference), 'wb')
    writer = UnicodeWriter(g)


    for row in reader:
        year = row[0]
        authors = []
        for name in row[1].split(','):
            try:
                cleanName = dblpNames[unidecode(name.strip()).strip()]
            except:
                cleanName = unidecode(name.strip()).strip()
            if len(cleanName):
                authors.append(cleanName)
        authors = ','.join(authors)
        writer.writerow([year, authors] + row[2:])

    g.close()

exit()



map = {
    "A. Di Maio": "Andrea Di Maio",
    "A. Fuggetta": "Alfonso Fuggetta",
    "Aaron Larson": "Aaron A. Larson",
    "Aaron Visaggio": "Corrado Aaron Visaggio",
    "Adam Nasr": "Khalid Adam Nasr",
    "Adam Porter": "Adam A. Porter",
    "Aditya Mathur": "Aditya P. Mathur",
    "Aditya Nori": "Aditya V. Nori",
    "Akos Kiss": "Akos Kiss 0001",
    "Alan Brown": "Alan W. Brown",
    "Alan Hu": "Alan J. Hu",
    "Alan Whitehurst": "R. Alan Whitehurst",
    "Alastair David Reid": "Alastair D. Reid",
    "Alastair Reid": "Alastair D. Reid",
    "Albert Zuendorf": "Albert Zundorf",
    "Alex Borgida": "Alexander Borgida",
    "Alex Kotov": "Alexander Kotov",
    "Alex Orso": "Alessandro Orso",
    "Alex Salcianu": "Alexandru Salcianu",
    "Alex Telea": "Alexandru Telea",
    "Alexander Wolf": "Alexander L. Wolf",
    "Alexandros Chatzigeorgiou": "Alexander Chatzigeorgiou",
    "Alexandru C. Telea": "Alexandru Telea",
    "Alexandru D. Salcianu": "Alexandru Salcianu",
    "Alfred W. Strohmeier": "Alfred Strohmeier",
    "Ali Razavi": "Alireza Razavi",
    "Alistair Sutcliffe": "Alistair G. Sutcliffe",
    "Amie Souter": "Amie L. Souter",
    "Amnon Eden": "Amnon H. Eden",
    "Amy Murphy": "Amy L. Murphy",
    "Ana Cavalli": "Ana R. Cavalli",
    "Ana Moreno": "Ana M. Moreno",
    "Anders Moller": "Anders L. B. Moller",
    "Andrea Skarra": "Andrea H. Skarra",
    "Andrew Bernat": "Andrew R. Bernat",
    "Andrew Malton": "Andrew J. Malton",
    "Andrew Symonds": "Andrew J. Symonds",
    "Andrew Tolmach": "Andrew P. Tolmach",
    "Andrey Terekhov": "Andrey A. Terekhov",
    "Andy Meneely": "Andrew Meneely",
    "Andy Schuerr": "Andy Schurr",
    "Anh Nguyen": "Hoan Anh Nguyen",
    "Anh Tuan Nguyen":"Hoan Anh Nguyen",
    "Aniruddha Gokhale": "Aniruddha S. Gokhale",
    "Annervaz K M":"K. M. Annervaz",
    "Annie Anton": "Annie I. Anton",
    "Annie Ying": "Annie T. T. Ying",
    "Anthony Hall": "Anthony D. Hall",
    "Arie Van Deursen": "Arie van Deursen",
    "Armando Haeberer": "Armando Martin Haeberer",
    "Arosha Bandara": "Arosha K. Bandara",
    "Arthur Reyes": "Arthur Alexander Reyes",
    "Artur Garcez": "Artur S. d'Avila Garcez",
    "Arvind Krishna": "Arvind S. Krishna",
    "Atanas (Nasko) Rountev": "Atanas Rountev",
    "Avinash Kak":"Avinash C. Kak",
    "Axel Van Lamsweerde": "Axel van Lamsweerde",
    "B. Magnusson": "Boris Magnusson",
    "B.M. Mainul Hossain": "B. M. Mainul Hossain",
    "Barbara Kitchenham": "Barbara A. Kitchenham",
    "Barry Boehm": "Barry W. Boehm",
    "Bart Jacobs": "Bart Jacobs 0002",
    "Barton Miller": "Barton P. Miller",
    "Benjamin Zorn": "Benjamin G. Zorn",
    "Bernd Fischer": "Bernd Fischer 0002",
    "Bernd Fischer": "Bernd M. Fischer",
    "Bernd Freimut": "Bernd G. Freimut",
    "Bernd Kraemer": "Bernd J. Kramer",
    "Bernhard Aichernig": "Bernhard K. Aichernig",
    "Betty Cheng": "Betty H. C. Cheng",
    "Beverly Sanders": "Beverly A. Sanders",
    "Bonnie John": "Bonnie E. John",
    "Brad Martin": "Bradley C. Martin",
    "Bradford Ulery": "Bradford T. Ulery",
    "Bradley Schmerl": "Bradley R. Schmerl",
    "Bran V. Selic": "Bran Selic",
    "Brenda Baker": "Brenda S. Baker",
    "Brian Bailey": "Brian P. Bailey",
    "Brian Ellis": "Brian J. Ellis",
    "Brian Robinson": "Brian P. Robinson",
    "Bruce Horowitz": "Bruce M. Horowitz",
    "Bruce Krogh": "Bruce H. Krogh",
    "C. Heitmeyer": "Constance L. Heitmeyer",
    "Carl Worms": "Carl F. Worms",
    "Carlo Alberto Furia": "Carlo A. Furia",
    "Carlos J.P. Lucena": "Carlos Jose Pereira de Lucena",
    "Carolyn Seaman": "Carolyn B. Seaman",
    "Catalin Roman": "Gruia-Catalin Roman",
    "Cecilia Mary F. Rubira": "Cecilia M. F. Rubira",
    "Cecilia Mary F. Rubira": "Cecilia Mary Fischer Rubira",
    "Chanchal K. Roy": "Chanchal Kumar Roy",
    "Chanchal Roy": "Chanchal Kumar Roy",
    "Chao Liu": "Chao Liu 0001",
    "Charles Haley": "Charles B. Haley",
    "Charles Knutson": "Charles D. Knutson",
    "Chris Holland": "Christopher P. Holland",
    "Chris Kemerer": "Chris F. Kemerer",
    "Chris Marlin": "Chris D. Marlin",
    "Chris Schofield": "Christopher J. Schofield",
    "Chris van der Westhuizen": "Christopher van der Westhuizen",
    "Christian Lange": "Christian F. J. Lange",
    "Christina Cifuentes": "Cristina Garcia Cifuentes",
    "Christoph Kessler": "Christoph W. Kessler",
    "Christoph Schaefer": "Christoph A. Schaefer",
    "Christopher Hughes": "Christopher J. Hughes",
    "Christopher Lott": "Christopher M. Lott",
    "Christopher Pidgeon": "Christopher W. Pidgeon",
    "Clemens Szyperski": "Clemens A. Szyperski",
    "Clement McGowan": "Clement L. McGowan",
    "Colin Fidge": "Colin J. Fidge",
    "Colin Mallows": "Colin L. Mallows",
    "Colin Potts": "Colin M. Potts",
    "Collin Mcmillan": "Collin McMillan",
    "Connie Heitmeyer": "Constance L. Heitmeyer",
    "Constance Heitmeyer": "Constance L. Heitmeyer",
    "Corina Pasareanu": "Corina S. Pasareanu",
    "Craig Wittenberg": "Craig H. Wittenberg",
    "Cristina Cifuentes": "Cristina Garcia Cifuentes",
    "Cristina Lopes": "Cristina V. Lopes",
    "Cristina Lopes": "Cristina Videira Lopes",
    "Cyrus Hall": "Cyrus P. Hall",
    "D. Natale": "Domenico Natale",
    "D. Rombach": "H. Dieter Rombach",
    "D.Yankelevich": "Daniel Yankelevich",
    "Dag Sjoberg": "Dag I. K. Sjoberg",
    "Dallas Webster": "Dallas E. Webster",
    "Dalton Dario Serey Guerrero": "Dalton Serey Guerrero",
    "Dan Grossman": "Daniel B. Grossman",
    "Daniel Berry": "Daniel M. Berry",
    "Daniel German": "Daniel M. German",
    "Daniel Grossman": "Daniel B. Grossman",
    "Daniel Jackson": "Daniel B. Jackson",
    "Daniel Laurence Moody": "Daniel L. Moody",
    "Daniel LE METAYER": "Daniel Le Metayer",
    "Daniel Moody": "Daniel L. Moody",
    "Daniel Waddington": "Dan G. Waddington",
    "Daniel Yellin": "Daniel M. Yellin",
    "Daniela S. Cruzes": "Daniela Cruzes",
    "Danny Groenewegen": "Danny M. Groenewegen",
    "Dany Yankelevich": "Daniel Yankelevich",
    "Dave Binkley": "David Binkley",
    "Dave Binkley": "David M. Binkley",
    "Dave Card": "David N. Card",
    "Dave King": "Dave King 0002",
    "Dave Robson": "David J. Robson",
    "Dave Wonnacott": "David Wonnacott",
    "David Atkins": "David L. Atkins",
    "David Barstow": "David R. Barstow",
    "David Basin": "David A. Basin",
    "David Binkley": "David M. Binkley",
    "David Bustard": "David W. Bustard",
    "David Eichmann": "David A. Eichmann",
    "David Harris": "David R. Harris",
    "David Huw Jones": "David H. Jones",
    "David Jones": "David H. Jones",
    "David Keyes": "David S. Keyes",
    "David Mason": "David V. Mason",
    "David Weiss": "David M. Weiss",
    "David Wile": "David S. Wile",
    "Dawson Engler": "Dawson R. Engler",
    "Debra Richardson": "Debra J. Richardson",
    "Dennis Smith": "Dennis B. Smith",
    "Devaraj George": "George Devaraj",
    "Dewayne Perry": "Dewayne E. Perry",
    "Dieter Rombach": "H. Dieter Rombach",
    "Dines Bjrner": "Dines Bjorner",
    "Domenico de Natale": "Domenico Natale",
    "Dominique MERY": "Dominique Mery",
    "Don Batory": "Don S. Batory",
    "Donald Pazel": "Donald P. Pazel",
    "Doris Carver": "Doris L. Carver",
    "Dorothy Setliff": "Dorothy E. Setliff",
    "Doug Kimelman": "Douglas N. Kimelman",
    "Douglas Schmidt": "Douglas C. Schmidt",
    "Duala-Ekoko": "Ekwa Duala-Ekoko",
    "E. Hull": "Emily Hull",
    "Earl Barr": "Earl T. Barr",
    "Edwin Chan": "Edwin C. Chan",
    "Edwin Westbrook": "Edwin M. Westbrook",
    "Elisa Baniassad": "Elisa L. A. Baniassad",
    "Elizabeth Leonard": "Elizabeth I. Leonard",
    "Elliot Chikofsky": "Elliot J. Chikofsky",
    "Elmar Juergens":"Elmar Jurgens",
    "Emery Berger": "Emery D. Berger",
    "Eric Dashofy": "Eric M. Dashofy",
    "Eric Eide": "Eric Norman Eide",
    "Eric Schoen": "Eric D. Schoen",
    "Ettore M. Merlo": "Ettore Merlo",
    "Ewan Tempero": "Ewan D. Tempero",
    "F. De Paoli": "Flavio De Paoli",
    "F. Paulisch": "Frances Paulisch",
    "F. van der Linden": "Frank van der Linden",
    "Fadi Zaraket": "Fadi A. Zaraket",
    "Fethi Rabhi": "Fethi A. Rabhi",
    "Filipo Ricca": "Filippo Ricca",
    "Francesco Sorrentino": "Francesco Sorrentino 0002",
    "Frank Calliss": "Frank W. Calliss",
    "Frank Shipman": "Frank M. Shipman III",
    "Fred Schneider": "Fred B. Schneider",
    "G. Leavens": "Gary T. Leavens",
    "G. Renardel de Lavalette": "Gerard R. Renardel de Lavalette",
    "Gail Kaiser": "Gail E. Kaiser",
    "Gang Huang": "Gang Huang 0001",
    "Gary Anderson": "Gary E. Anderson",
    "Gary Leavens": "Gary T. Leavens",
    "Gary T. LEAVENS": "Gary T. Leavens",
    "George Avrunin": "George S. Avrunin",
    "George Baah": "George K. Baah",
    "George Heineman": "George T. Heineman",
    "George Stark": "George E. Stark",
    "George Wilkie": "F. George Wilkie",
    "Gerald Gannod": "Gerald C. Gannod",
    "Gerard Holzmann": "Gerard J. Holzmann",
    "Gerhard Fischer": "Gerhard G. Fischer",
    "German Rivera": "German M. Rivera",
    "German Sibay": "German E. Sibay",
    "Ghizlane El Boussaidi": "Ghizlane El-Boussaidi",
    "Giacomo Sechi": "Giacomo R. Sechi",
    "Gina Venolia": "Gina Danielle Venolia",
    "Giuseppe Di Lucca": "Giuseppe A. Di Lucca",
    "Gordon Blair": "Gordon S. Blair",
    "Gordon Novak": "Gordon S. Novak",
    "Grace Lewis": "Grace A. Lewis",
    "Gregory Gay": "Gregory R. Gay",
    "Gregory Kapfhammer": "Gregory M. Kapfhammer",
    "Gregory Wilson": "Gregory V. Wilson",
    "Gul Agha": "Gul A. Agha",
    "Gunnar Bergersen": "Gunnar R. Bergersen",
    "Guoqing (Harry) Xu": "Guoqing Xu",
    "Gursimran Singh Walia": "Gursimran S. Walia",
    "Gursimran Walia": "Gursimran S. Walia",
    "H. Mossenbock": "Hanspeter Mossenbock",
    "H. Muller": "Hausi A. Muller",
    "H. Obbink": "J. Henk Obbink",
    "H. Saiedian": "Hossein Saiedian",
    "H. Toetenel": "Hans Toetenel",
    "H.-Arno Jacobsen": "Hans-Arno Jacobsen",
    "Hakam Alomari": "Hakam W. Alomari",
    "Hannu-Matti Jaervinen": "Hannu-Matti Jarvinen",
    "Hans Kohler": "Hans J. Kohler",
    "Harald Gall": "Harald C. Gall",
    "Haroon Babri": "Haroon A. Babri",
    "Harry Sneed": "Harry M. Sneed",
    "Hausi Mueller": "Hausi A. Muller",
    "Hausi Muller": "Hausi A. Muller",
    "Helen Edwards": "Helen M. Edwards",
    "Helen Sharp": "Helen C. Sharp",
    "Heng Lu": "Heng Lu 0001",
    "Herbert Prhofer": "Herbert Prahofer",
    "Hernan Melgratti": "Hernan C. Melgratti",
    "Hoan Nguyen": "Hoan Anh Nguyen",
    "Holger Kienle": "Holger M. Kienle",
    "Howard Shrobe": "Howard E. Shrobe",
    "Hsiang-Jui Kungs": "Hsiang-Jui Kung",
    "I. Sommerville": "Ian Sommerville",
    "Ian Bull": "R. Ian Bull",
    "Ian Peake": "Ian D. Peake",
    "Iida Hajimu": "Hajimu Iida",
    "Ingolf Kruger": "Ingolf H. Kruger",
    "Ioannis Kotsiopoulos": "Ioannis A. Kotsiopoulos",
    "Ira Baxter": "Ira D. Baxter",
    "Ira Smith": "Ira A. Smith",
    "Istvan Forgas": "Istvan Forgacs",    
    "J. A. de La Puente": "Juan Antonio de la Puente",
    "J. C. Derniame": "Jean-Claude Derniame",
    "J. Cook": "Jonathan E. Cook",
    "J. Kramer": "Jeff Kramer",
    "J. Kuusela": "Juha Kuusela",
    "J. Palsberg": "Jens Palsberg",
    "J. Taramaa": "Jorma Taramaa",
    "J. Welsh": "Jim Welsh",
    "Jack Wileden": "Jack C. Wileden",
    "James Bowring": "James F. Bowring",
    "James Browne": "James C. Browne",
    "James Clause": "James A. Clause",
    "James Corbett": "James C. Corbett",
    "James Cross II": "James H. Cross II",
    "James Herbsleb": "James D. Herbsleb",
    "James Larus": "James R. Larus",
    "James Law": "James B. Law",
    "James Leathrum": "James F. Leathrum",
    "James Neighbors": "James M. Neighbors",
    "James Noble": "James S. Noble",
    "James Purtilo": "James M. Purtilo",
    "James Terwilliger": "James F. Terwilliger",
    "Jamieson Cobleigh": "Jamieson M. Cobleigh",
    "Janice Singer": "Janice A. Singer",
    "Jason King": "Jason S. King",
    "Jason Mansell": "Jason Xabier Mansell",
    "Jean Claude Derniame": "Jean-Claude Derniame",
    "Jeannette Wing": "Jeannette M. Wing",
    "Jeff Magee": "Jeffrey N. Magee",
    "Jeff N. Magee": "Jeffrey N. Magee",
    "Jeffery Van Baalen": "Jeffrey Van Baalen",
    "Jeffrey Foster": "Jeffrey S. Foster",
    "Jelber Sayyad Shirabad": "Jelber Sayyad-Shirabad",
    "Jenny Zou": "Ying Zou",
    "Jens Jahnke": "Jens H. Jahnke",
    "Jereme Haack": "Jereme N. Haack",
    "Jeremy Siek": "Jeremy G. Siek",
    "Jesus M. Gonzales-Barahona": "Jesus M. Gonzalez-Barahona",
    "Jia-Su Sun": "Jiasu Sun",
    "Jiang Zheng": "Jiang Zheng 0001",
    "Jim Bieman": "James M. Bieman",
    "Jim Cordy": "James R. Cordy",
    "Jim Gish": "James W. Gish",
    "Jim Ning": "Jim Q. Ning",
    "Jim Qun Ning": "Jim Q. Ning",
    "Jing Sun": "Jing Sun 0002",
    "Jo Atlee": "Joanne M. Atlee",
    "Joanne Atlee": "Joanne M. Atlee",
    "Joao Pedro Sousa": "Joao P. Sousa",
    "Joao Sousa": "Joao P. Sousa",
    "Jochen M. Kuester": "Jochen M. Kuster",
    "John Chaves": "John A. Chaves",
    "John Criswell": "John R. Criswell",
    "John Edwards": "John M. Edwards",
    "John Field": "John P. Field",
    "John Gannon": "John D. Gannon",
    "John Grundy": "John C. Grundy",
    "John Hosking": "John G. Hosking",
    "John Keane": "John A. Keane",
    "John Knight": "John C. Knight",
    "John Powell": "John D. Powell",
    "John Rushby": "John M. Rushby",
    "John Walker": "John J. Walker",
    "Jonathan Bowen": "Jonathan P. Bowen",
    "Jonathan Cook": "Jonathan E. Cook",
    "Jonathan Moffett": "Jonathan D. Moffett",
    "Jonathan Whittle": "Jonathan P. Whittle",
    "Jorge Figueiredo": "Jorge C. A. de Figueiredo",
    "Jose Fiadeiro": "Jose Luiz Fiadeiro",
    "Jose L Arciniegas": "Jose L. Arciniegas",
    "Joseph Goguen": "Joseph A. Goguen",
    "Joseph Horgan": "Joseph R. Horgan",
    "Joseph Near": "Joseph P. Near",
    "Joseph Robert Horgan": "Joseph R. Horgan",
    "Juan Carlos Duenas": "Juan C. Duenas",
    "Juan Carlos Granja Alvarez": "Juan Carlos Granja-Alvarez",
    "Juan Fernandez Ramil": "Juan Fernandez-Ramil",
    "Juan Ramil": "Juan F. Ramil",
    "Juergen Dingel": "Juergen DingelJuergen Dingel",
    "Julia Lawall": "Julia L. Lawall",
    "Julio Cesar Leite": "Julio Cesar Sampaio do Prado Leite",
    "Jun Li": "Jun Li 0008",
    "Jun Sun": "Jun Sun 0001",
    "Jurgen Rilling": "Juergen Rilling",
    "Jurgen Vinju": "Jurgen J. Vinju",
    "Jyotirmoy Deshmukh": "Jyotirmoy V. Deshmukh",
    "K. Koskimies": "Kai Koskimies",
    "K. Nakakoji": "Kumiyo Nakakoji",
    "Karen Huff": "Karen E. Huff",
    "Kari Nies": "Kari A. Nies",
    "Karl Lieberherr": "Karl J. Lieberherr",
    "Kathy Davis": "Kathi Hogshead Davis",
    "Keith Bennett": "Keith H. Bennett",
    "Kenichi Matsumoto": "Ken-ichi Matsumoto",
    "Kenichi Matsumoto": "Kenichiro Matsumoto",
    "Kenneth Anderson": "Kenneth M. Anderson",
    "Kenneth Frazier": "Kenneth B. Frazier",
    "Kenneth Mark Anderson": "Kenneth M. Anderson",
    "Kevin Hoffman": "Kevin J. Hoffman",
    "Kevin Sullivan": "Kevin J. Sullivan",
    "Klaus Hennig": "Klaus Henning",
    "Kong Weiqiang": "Weiqiang Kong",
    "Kris de Volder": "Kris De Volder",
    "Krishna Mehra": "Krishna K. Mehra",
    "Kurt Stirewalt": "R. E. Kurt Stirewalt",
    "Kyle Canavera": "Kyle R. Canavera",
    "Lajos Jeno": "Lajos Jeno Fulop",
    "Larry Markosian": "Lawrence Markosian",
    "Laura Dillon": "Laura K. Dillon",
    "Laurie DILLON": "Laurie Dillon",
    "Laurie Williams": "Laurie A. Williams",
    "Lawrence G. Votta Jr.": "Lawrence G. Votta",
    "Lawrence Votta": "Lawrence G. Votta",
    "Lee Osterweil": "Leon J. Osterweil",
    "Lee White": "Lee J. White",
    "Lei Wang": "Lei Wang 0018",
    "Lennart Kats": "Lennart C. L. Kats",
    "Leopoldo Bertossi": "Leopoldo E. Bertossi",
    "Letha Hughes Etzkorn": "Letha H. Etzkorn",
    "Lewis Johnson": "W. Lewis Johnson",
    "Li Zhang": "Li Zhang 0004",
    "Linda Northrop": "Linda M. Northrop",
    "Linda Wills": "Linda M. Wills",
    "Lingxiao JIANG": "Lingxiao Jiang",
    "Liwu Li": "Liwu Li 0001",
    "Loren Terveen": "Loren G. Terveen",
    "Lori Pollock": "Lori L. Pollock",
    "Lu Zhang": "Lu Zhang 0023",
    "Lucas Panjer": "Lucas D. Panjer",
    "Luciano Da Fontoura Costa": "Luciano da Fontoura Costa",
    "M. Dwyer": "Matthew B. Dwyer",
    "M. Glinz": "Martin Glinz",
    "M. Harrold": "Mary Jean Harrold",
    "M. Hinchey": "Michael G. Hinchey",
    "M. Pezze": "Mauro Pezze",
    "M. Sitaraman": "Murali Sitaraman",
    "Madhusudan Parthasarathy":"P. Madhusudan",
    "Magnus Larsson": "Magnus E. Larsson",
    "Maja d'Hondt": "Maja D'Hondt",
    "Malay Ganai": "Malay K. Ganai",
    "Mamadou Diallo": "Mamadou H. Diallo",
    "Manny Lehman": "Meir M. Lehman",
    "Manoel Mendonca": "Manoel G. Mendonca",
    "Marc Kellner": "Marc I. Kellner",
    "Marcela Fabiana Genero Bocco": "Marcela Genero Bocco",
    "Marcelo Fabiun Frias": "Marcelo F. Frias",
    "Marcelo Frias": "Marcelo F. Frias",
    "Marco Tulio Valente": "Marco Tulio de Oliveira Valente",
    "Margaret Burnett": "Margaret M. Burnett",
    "Margaret Lyell": "Margaret J. Lyell",
    "Margaret Smith": "Margaret H. Smith",
    "Mariano Moscato": "Mariano M. Moscato",
    "Mariella Tortorella": "Maria Tortorella",
    "Mario Linares-Vasquez": "Mario Linares Vásquez",
    "Marius Bogdan Spinu": "Marius B. Spinu",
    "Mark Alan Jones": "Mark A. Jones",
    "Mark Jones": "Mark A. Jones",
    "Mark Linton": "Mark A. Linton",
    "Mark Van Den Brand": "Mark G. J. van den Brand",
    "Marlon DUMAS": "Marlon Dumas",
    "Marta Kwiatkowska": "Marta Z. Kwiatkowska",
    "Martin GLINZ": "Martin Glinz",
    "Martin Griss": "Martin L. Griss",
    "Martin Grosse Rhode": "Martin Grosse-Rhode",
    "Martin Robillard": "Martin P. Robillard",
    "Martin Sheppard": "Martin J. Shepperd",
    "Martin Shepperd": "Martin J. Shepperd",
    "Martin Ward": "Martin P. Ward",
    "Mary Fernandez": "Mary F. Fernandez",
    "Mary Hall": "Mary W. Hall",
    "Mary Shaw": "Mary M. Shaw",
    "Mathew Flatt": "Matthew Flatt",
    "Mats Heimdahl": "Mats Per Erik Heimdahl",
    "Matt Dwyer": "Matthew B. Dwyer",
    "Matt Dwyer":"Matthew B. Dwyer",
    "Matthew Dwyer": "Matthew B. Dwyer",
    "Matthew Marcus": "Matthew A. Marcus",
    "Matthias Wagner": "Matthias Wagner 0001",
    "Md Kamal Hossen": "Kamal Hossen",
    "Mehdi Harandi": "Mehdi T. Harandi",
    "Mehmet Orgun": "Mehmet A. Orgun",
    "Melissa Chase": "Melissa P. Chase",
    "Michael Blaha": "Michael R. Blaha",
    "Michael Cusumano": "Michael A. Cusumano",
    "Michael Ernst": "Michael D. Ernst",
    "Michael Houle": "Michael E. Houle",
    "Michael Loewe": "Michael Lowe",
    "Michael Lyu": "Michael R. Lyu",
    "Michael Muller": "Michael J. Muller",
    "Michael Olsem": "Michael R. Olsem",
    "Michael Van De Vanter": "Michael L. Van de Vanter",
    "Michael Whalen": "Michael W. Whalen",
    "Michel Chaudron": "Michel R. V. Chaudron",
    "Michelle Strout": "Michelle Mills Strout",
    "Mike Papazoglou": "Mike P. Papazoglou",
    "Mike Schrank": "Michael Schrank",
    "Mira Kajko-Mattson": "Mira Kajko-Mattson",
    "Mira Kajko-Mattson": "Mira Kajko-Mattsson",
    "Miriam Capretz": "Miriam A. M. Capretz",
    "Mitch Lubars": "Mitchell D. Lubars",
    "Mohammed El Ramly": "Mohammad El-Ramly",
    "Monica Lam": "Monica S. Lam",
    "Morven Gentleman": "W. Morven Gentleman",
    "Muhammad Naeem": "Muhammad Naeem 0002",
    "Myra Cohen": "Myra B. Cohen",
    "Nabor Mendonca": "Nabor C. Mendonca",
    "Naftaly Minsky": "Naftaly H. Minsky",
    "Nancy Day": "Nancy A. Day",
    "Nancy Leveson": "Nancy G. Leveson",
    "Narciso Marti Oliet": "Narciso Marti-Oliet",
    "Naser Barghouti": "Naser S. Barghouti",
    "Natalia Juristo": "Natalia Juristo Juzgado",
    "Neil Maiden": "Neil A. M. Maiden",
    "Nenad Medvidovich": "Nenad Medvidovic",
    "Nguyen Thanh Binh": "Thanh Binh Nguyen 0002",
    "Nicholas Chen": "Nicholas Y. Chen",
    "Nicholas Kraft": "Nicholas A. Kraft",
    "Nicolas Gold": "Nicolas E. Gold",
    "Niels Veerman": "Niels P. Veerman",
    "Nikolaj Bjoerner": "Nikolaj Bjorner",
    "Norman Schneidewind": "Norman F. Schneidewind",
    "Oscar NIERSTRASZ": "Oscar Nierstrasz",
    "P. Botella": "Pere Botella",
    "P. Garg": "Pankaj K. Garg",
    "P. Kroha": "Petr Kroha",
    "P. Zave": "Pamela Zave",
    "Pamela ZAVE": "Pamela Zave",
    "Pankaj Garg": "Pankaj K. Garg",
    "Panos Linos": "Panagiotis K. Linos",
    "Parthasarathy Madhusudan": "P. Madhusudan",
    "Pasi Kavaja": "Pasi Kuvaja",
    "Patricia Oberndorf": "Patricia A. Oberndorf",
    "Patrick Maeder":"Patrick Mader",
    "Paul A Bailes": "Paul A. Bailes",
    "Paul Bailes": "Paul A. Bailes",
    "Paul Bailor": "Paul D. Bailor",
    "Paul Bannerman": "Paul L. Bannerman",
    "Paul Clements": "Paul C. Clements",
    "Paul Dan Marinescu": "Paul Marinescu",
    "Paul Gruenbacher": "Paul Grunbacher",
    "Paul Layzell": "Paul J. Layzell",
    "Paul Oman": "Paul W. Oman",
    "Paul Sorenson": "Paul G. Sorenson",
    "Paul Steckler": "Paul A. Steckler",
    "Paul Strooper": "Paul A. Strooper",
    "Paulo Masiero": "Paulo Masiero Masiero",
    "Paulo R. F. Cunha": "Paulo Cunha",
    "Pedro D'Argenio": "Pedro R. D'Argenio",
    "Pedro Dias Guerreiro": "Pedro Guerreiro",
    "Peri Tarr": "Peri L. Tarr",
    "Peter Feiler": "Peter H. Feiler",
    "Peter Mehlitz": "Peter C. Mehlitz",
    "Peter Mosses": "Peter D. Mosses",
    "Peter Olveczky": "Peter Csaba Olveczky",
    "Peter Rigby": "Peter C. Rigby",
    "Phyllis Frankl": "Phyllis G. Frankl",
    "Pinto Carlos": "Carlos Pinto",
    "Prasanta Bose": "Prasanta K. Bose",
    "Prem Devanbu": "Premkumar T. Devanbu",
    "Qin Ma": "Qin Ma 0002",
    "R. Conradi": "Reidar Conradi",
    "R. Kemmerer": "Richard A. Kemmerer",
    "R. Klosch": "Rene Klosch",
    "Rachel Bellamy": "Rachel K. E. Bellamy",
    "Raimund Feldmann": "Raimund L. Feldmann",
    "Raj Sood": "H. Raj Sood",
    "Rajseh Vasa": "Rajesh Vasa",
    "Ralf Kollman": "Ralf Kollmann",
    "Ralf Laemmel": "Ralf Lammel",
    "Ralf Reussner": "Ralf H. Reussner",
    "Ralph Johnson": "Ralph E. Johnson",
    "Randy Howard Katz": "Randy H. Katz",
    "Randy Katz": "Randy H. Katz",
    "Raul Santelices": "Raul A. Santelices",
    "Ravi Sandhu": "Ravi S. Sandhu",
    "Reiner Dumke": "Reiner R. Dumke",
    "Rene Kloesch": "Rene Klosch",
    "Rene Krikhaar": "Rene L. Krikhaar",
    "Rene R. Kloesch": "Rene Klosch",
    "Ric Holt": "Richard C. Holt",
    "Richard Paige": "Richard F. Paige",
    "Richard Piazza": "Richard L. Piazza",
    "Richard Taylor": "Richard N. Taylor",
    "Rob Hierons": "Robert M. Hierons",
    "Rob Miller": "Rob Miller 0003",
    "Rob Rist": "Robert S. Rist",
    "Robert Arnold": "Robert S. Arnold",
    "Robert Bowdidge": "Robert W. Bowdidge",
    "Robert Filman": "Robert E. Filman",
    "Robert France": "Robert B. France",
    "Robert Fuhrer": "Robert M. Fuhrer",
    "Robert Griffiths": "Robert P. Griffiths",
    "Robert Hierons": "Robert M. Hierons",
    "Robert Mays": "Robert G. Mays",
    "Roberto A. Bittencourt": "Roberto Almeida Bittencourt",
    "Roberto Lopez-Herrejon": "Roberto E. Lopez-Herrejon",
    "Roberto Silva Filho": "Roberto Silveira Silva Filho",
    "Robyn Lutz": "Robyn R. Lutz",
    "Roger Khazan": "Roger I. Khazan",
    "Roland Mittermeir": "Roland T. Mittermeir",
    "Ross Jeffery": "D. Ross Jeffery",
    "Ruth BREU": "Ruth Breu",
    "S. C. Cheung": "Shing-Chi Cheung",
    "S. D. Swierstra": "S. Doaitse Swierstra",
    "S. Feldman": "Stuart I. Feldman",
    "S. Jerome Carriere": "S. Jeromy Carriere",
    "S.C. Cheung": "Shing-Chi Cheung",
    "Saleh Alnaeli": "Saleh M. Alnaeli",
    "Sales Pinto": "Leandro Sales Pinto",
    "Sandeep Shukla": "Sandeep K. Shukla",
    "Saumya Debray": "Saumya K. Debray",
    "Scanniello Giuseppe": "Giuseppe Scanniello",
    "Scott Ankrum": "T. Scott Ankrum",
    "Scott Fahlman": "Scott E. Fahlman",
    "Scott Fleming": "Scott D. Fleming",
    "Scott Tilley": "Scott R. Tilley",
    "Sean Falconer": "Sean M. Falconer",
    "Sebastian Elbaum": "Sebastian G. Elbaum",
    "Shauvik Roy": "Shauvik Roy Choudhary",
    "Shawn Bohner": "Shawn A. Bohner",
    "Shawn Butler": "Shawn A. Butler",
    "Siau Cheng Khoo": "Siau-Cheng Khoo",
    "Simon Holland": "Simon T. Holland",
    "Simon Kaplan": "Simon M. Kaplan",
    "Simon Peyton Jones": "Simon L. Peyton Jones",
    "Sol Greenspan": "Sol J. Greenspan",
    "Sriram Rajamani": "Sriram K. Rajamani",
    "Stan Zdonik": "Stanley B. Zdonik",
    "Stephen Blackburn": "Stephen M. Blackburn",
    "Stephen Cook": "Stephen Cook 0002",
    "Stephen Fink": "Stephen J. Fink",
    "Stephen Foster": "Stephen R. Foster",
    "Stephen Siegel": "Stephen F. Siegel",
    "Steve Easterbrook": "Steve M. Easterbrook",
    "Steve Fickas": "Stephen Fickas",
    "Steve MacDonell": "Steven G. MacDonell",
    "Steve Reiss": "Steven P. Reiss",
    "Steve S. Yau": "Stephen S. Yau",
    "Steven Brown": "Steven W. Brown",
    "Steven Easterbrook": "Steve M. Easterbrook",
    "Steven Woods": "Steven G. Woods",
    "Stuart Faulk": "Stuart R. Faulk",
    "Stuart Kent": "Stuart T. Kent",
    "Suraj Kothari": "Suraj C. Kothari",
    "Susan Gerhart": "Susan L. Gerhart",
    "Susan Graham": "Susan L. Graham",
    "Sushil Bajracharya": "Sushil Krishna Bajracharya",
    "Swee-Cheang Lim": "Lim Swee Cheang",
    "T. Ellman": "Thomas Ellman",
    "Taghi Khoshgoftaar": "Taghi M. Khoshgoftaar",
    "Ted Biggerstaff": "Ted J. Biggerstaff",
    "Teresa Baldassarre": "Maria Teresa Baldassarre",
    "Tereza Kirner": "Tereza G. Kirner",
    "ThanhVu Nguyen": "ThanhVu H. Nguyen",
    "Theo d'Hondt": "Theo D'Hondt",
    "Thiago Bartolomei": "Thiago T. Bartolomei",
    "Thomas Alspaugh": "Thomas A. Alspaugh",
    "Thomas Ball": "Thomas A. Ball",
    "Thomas Dean": "Thomas R. Dean",
    "Thomas Dean": "Thomas Roy Dean",
    "Thomas Gross": "Thomas R. Gross",
    "Thomas J. McCabe Sr.": "Thomas J. McCabe",
    "Thomas LaToza": "Thomas D. LaToza",
    "Thomas Marlowe": "Thomas J. Marlowe",
    "Thuan Pham": "Thuan Q. Pham",
    "Tiago Alves": "Tiago L. Alves",
    "Tien Nhut Nguyen": "Tien N. Nguyen",
    "Tilmann Bruckhaus": "Tilmann F. W. Bruckhaus",
    "Tim Leek": "Timothy R. Leek",
    "Timothy Lethbridge": "Timothy C. Lethbridge",
    "Timothy Wright": "Timothy N. Wright",
    "Tobias Roetschke": "Tobias Rotschke",
    "Todd Millstein": "Todd D. Millstein",
    "Todd Veldhuizen": "Todd L. Veldhuizen",
    "Tom Ball": "Thomas A. Ball",
    "Tom Ellman": "Thomas Ellman",
    "Tom Reps": "Thomas W. Reps",
    "Tom Zimmermann": "Thomas Zimmermann",
    "Tooru Takeshita": "Toru Takeshita",
    "Tung Nguyen": "Tung T. Nguyen",
    "Tung Nguyen": "Tung Thanh Nguyen",
    "Ugo Buy": "Ugo A. Buy",
    "Ugo De Carlini": "Ugo de Carlini",
    "Umut Acar": "Umut A. Acar",
    "Vasu Alagar": "Vasu S. Alagar",
    "Victor Basili": "Victor R. Basili",
    "Victor Braberman": "Victor A. Braberman",
    "Victor Kasyanov": "Victor N. Kasyanov",
    "Vikrant Kaulgud": "Vikrant S. Kaulgud",
    "Vikrant Kaulgud":"Vikrant S. Kaulgud",
    "Vu Ha": "Vu A. Ha",
    "W. Agresti": "William W. Agresti",
    "W. Bischofberger": "Walter R. Bischofberger",
    "W. Emmerich": "Wolfgang Emmerich",
    "W. Glatthaar": "Wolfgang Glatthaar",
    "W. Griswold": "William G. Griswold",
    "W. K. Chan": "Wing Kwong Chan",
    "W. Melo": "Walcelio L. Melo",
    "W.J. Toetenel": "Hans Toetenel",
    "W.K. Chan": "Wing Kwong Chan",
    "Walcelio Melo": "Walcelio L. Melo",
    "Walter Scacchi": "Walt Scacchi",
    "Walter Tichy": "Walter F. Tichy",
    "Wilhelm Schaefer": "Wilhelm Schafer",
    "Will Dietz": "William Dietz",
    "Will Tracz": "William J. Tracz",
    "Willem C. Visser": "Willem Visser",
    "William Agresti": "William W. Agresti",
    "William Griswold": "William G. Griswold",
    "William Halfond": "William G. J. Halfond",
    "William Marsh": "William E. Marsh",
    "William Robinson": "William N. Robinson",
    "William Scherlis": "William L. Scherlis",
    "Xiangyu Zhang": "Xiangyun Zhang",
    "Xiaoqing (Frank) Liu": "Xiaoqing Liu",
    "Xiaoqing Frank Liu": "Xiaoqing Liu",
    "Xiaoyin Wang": "Xiaoying Wang",
    "Xin (Shin) Zhang": "Xin Zhang",
    "Yanhong Annie Liu": "Yanhong A. Liu",
    "Yannis Kanellopoulos": "Yiannis Kanellopoulos",
    "Ye Zhang": "Ye Zhang 0002",
    "Yiannis Vassiliou": "Yannis Vassiliou",
    "Yih-Farn Robin Chen": "Yih-Farn Chen",
    "Ying (Jenny) Zou": "Ying Zou",
    "Yong-Mi Kim": "Yong-Min Kim",
    "Yuichiro Nakagawa": "Yuichiroh Nakagawa",
    
    "Ahmed Hassan": "Ahmed E. Hassan",
    "Aiko Yamashita": "Aiko Fallas Yamashita",
    "Amit Paradkar": "Amit M. Paradkar",
    "Atif Memon": "Atif M. Memon",
    "Barbara Ryder": "Barbara G. Ryder",
    "Carlos Lucena": "Carlos Jose Pereira de Lucena",
    "Chandan Rupakheti": "Chandan Raj Rupakheti",
    "Dag I.K. Sjoberg": "Dag I. K. Sjoberg",
    "Daniel Rosenkrantz": "Daniel J. Rosenkrantz",
    "David Rosenblum": "David S. Rosenblum",
    "Edy Liongosari": "Edy S. Liongosari",
    "Emerson Murphy-Hill": "Emerson R. Murphy-Hill",
    "Gail Murphy": "Gail C. Murphy",
    "Giulio Antoniol": "Giuliano Antoniol",
    "Giuseppe Antonio di Lucca": "Giuseppe A. Di Lucca",
    "Harvey Siy": "Harvey P. Siy",
    "Houari Sahraoui": "Houari A. Sahraoui",
    "Hsiao Ming Tsou": "Hsiao-Ming Tsou",
    "Huzefa Kagdi": "Huzefa H. Kagdi",
    "Jafar Al-Kofahi": "Jafar M. Al-Kofahi",
    "James Cordy": "James R. Cordy",
    "James Jones": "James A. Jones",
    "Jean Marie Favre": "Jean-Marie Favre",
    "Jeremy Archuleta": "Jeremy S. Archuleta",
    "Jonathan Maletic": "Jonathan I. Maletic",
    "Kevin Conroy": "Kevin M. Conroy",
    "Lionel Briand": "Lionel C. Briand",
    "Luay H. Tahat": "Luay Ho Tahat",
    "Manar Alalfi": "Manar H. Alalfi",
    "Margaret-Anne Storey": "Margaret-Anne D. Storey",
    "Michael Collard": "Michael L. Collard",
    "Michael Godfrey": "Michael W. Godfrey",
    "Mike Godfrey": "Michael W. Godfrey",
    "Premkumar Devanbu": "Premkumar T. Devanbu",
    "Richard Holt": "Richard C. Holt",
    "Robert Walker": "Robert J. Walker",
    "Stephen MacDonell": "Stephen G. MacDonell",
    "Steven Reiss": "Steven P. Reiss",
    "Tien Nguyen": "Tien N. Nguyen",
    "Ulrich Nickel": "Ulrich Nickel 0002",
    "Vugranam Sreedhar": "Vugranam C. Sreedhar",
    "William Sumner": "William N. Sumner",
    "Zachary Fry": "Zachary P. Fry",

}

for key1, val1 in map.iteritems():
    for key2, val2 in map.iteritems():
        if key1 == val2:
            print key1, val1 
        if  key2 == val1:
            print key2, val2




dblpNames1 = {
    'Ahmed Hassan': 'Ahmed E. Hassan',
    'Aiko Yamashita': 'Aiko Fallas Yamashita',
    'Akos Kiss': 'Akos Kiss 0001',
    'Amit Paradkar': 'Amit M. Paradkar',
    'Andrew Bernat': 'Andrew R. Bernat',
    'Anh Nguyen': 'Hoan Anh Nguyen',
    'Anh Tuan Nguyen':'Hoan Anh Nguyen',
    'Annervaz K M':'K. M. Annervaz',
    'Atif Memon': 'Atif M. Memon',
    'Avinash Kak':'Avinash C. Kak',
    'B.M. Mainul Hossain': 'B. M. Mainul Hossain',
    'Barbara Ryder': 'Barbara G. Ryder',
    'Bart Jacobs': 'Bart Jacobs 0002',
    'Barton Miller': 'Barton P. Miller',
    'Bernd Fischer': 'Bernd Fischer 0002',
    'Brian Robinson': 'Brian P. Robinson',
    'Carlo Alberto Furia': 'Carlo A. Furia',
    'Carlos Lucena': 'Carlos Jose Pereira de Lucena',
    'Cecilia Mary F. Rubira': 'Cecilia M. F. Rubira',
    'Chanchal K. Roy': 'Chanchal Kumar Roy',
    'Chandan Rupakheti': 'Chandan Raj Rupakheti',
    'Chao Liu': 'Chao Liu 0001',
    'Cristina Lopes': 'Cristina Videira Lopes',
    'Dag I.K. Sjoberg': 'Dag I. K. Sjoberg',
    'Dalton Dario Serey Guerrero': 'Dalton Serey Guerrero',
    'Daniel Rosenkrantz': 'Daniel J. Rosenkrantz',
    'Daniela S. Cruzes': 'Daniela Cruzes',
    'Dave Binkley': 'David Binkley',
    'Dave King': 'Dave King 0002',
    'Edy Liongosari': 'Edy S. Liongosari',
    'Elmar Juergens':'Elmar Jurgens',
    'Emerson Murphy-Hill': 'Emerson R. Murphy-Hill',
    'Francesco Sorrentino': 'Francesco Sorrentino 0002',
    'Gail Murphy': 'Gail C. Murphy',
    'Gang Huang': 'Gang Huang 0001',
    'Ghizlane El Boussaidi': 'Ghizlane El-Boussaidi',
    'Giulio Antoniol': 'Giuliano Antoniol',
    'Giuseppe Antonio Di Lucca': 'Giuseppe A. Di Lucca',
    'Hakam Alomari': 'Hakam W. Alomari',
    'Harald C. Gall': 'Harald Gall',
    'Harvey Siy': 'Harvey P. Siy',
    'Heng Lu': 'Heng Lu 0001',
    'Hoan Nguyen': 'Hoan Anh Nguyen',
    'Houari Sahraoui': 'Houari A. Sahraoui',
    'Hsiao Ming Tsou': 'Hsiao-Ming Tsou',
    'Huzefa Kagdi': 'Huzefa H. Kagdi',
    'Ian Peake': 'Ian D. Peake',
    'Jafar Al-Kofahi': 'Jafar M. Al-Kofahi',
    'James Cordy': 'James R. Cordy',
    'James Jones': 'James A. Jones',
    'Jean Marie Favre': 'Jean-Marie Favre',
    'Jeremy Archuleta': 'Jeremy S. Archuleta',
    'Jia-Su Sun': 'Jiasu Sun',
    'Jiang Zheng': 'Jiang Zheng 0001',
    'Jing Sun': 'Jing Sun 0002',
    'Jonathan Maletic': 'Jonathan I. Maletic',
    'Jorge Figueiredo': 'Jorge C. A. de Figueiredo',
    'Joseph Near': 'Joseph P. Near',
    'Jun Li': 'Jun Li 0008',
    'Jun Sun': 'Jun Sun 0001',
    'Kenichi Matsumoto': 'Ken-ichi Matsumoto',
    'Kevin Conroy': 'Kevin M. Conroy',
    'Kyle Canavera': 'Kyle R. Canavera',
    'Lei Wang': 'Lei Wang 0018',
    'Li Zhang': 'Li Zhang 0004',
    'Lionel Briand': 'Lionel C. Briand',
    'Liwu Li': 'Liwu Li 0001',
    'Lu Zhang': 'Lu Zhang 0023',
    'Luay H. Tahat': 'Luay Ho Tahat',
    'Madhusudan Parthasarathy':'P. Madhusudan',
    'Malay Ganai': 'Malay K. Ganai',
    'Manar Alalfi': 'Manar H. Alalfi',
    'Marco Tulio Valente': 'Marco Tulio de Oliveira Valente',
    'Margaret-Anne Storey': 'Margaret-Anne D. Storey',
    'Matt Dwyer':'Matthew B. Dwyer',
    'Matthias Wagner': 'Matthias Wagner 0001',
    'Md Kamal Hossen': 'Kamal Hossen',
    'Michael Collard': 'Michael L. Collard',
    'Michael Godfrey': 'Michael W. Godfrey',
    'Michael Lyu': 'Michael R. Lyu',
    'Michael Muller': 'Michael J. Muller',
    'Mike Godfrey': 'Michael W. Godfrey',
    'Muhammad Naeem': 'Muhammad Naeem 0002',
    'Nguyen Thanh Binh': 'Thanh Binh Nguyen 0002',
    'Patrick Maeder':'Patrick Mader',
    'Premkumar Devanbu': 'Premkumar T. Devanbu',
    'Qin Ma': 'Qin Ma 0002',
    'Ralf Laemmel': 'Ralf Lammel',
    'Richard Holt': 'Richard C. Holt',
    'Rob Miller': 'Rob Miller 0003',
    'Robert Walker': 'Robert J. Walker',
    'Roberto A. Bittencourt': 'Roberto Almeida Bittencourt',
    'Saleh Alnaeli': 'Saleh M. Alnaeli',
    'Stephen Cook': 'Stephen Cook 0002',
    'Stephen MacDonell': 'Stephen G. MacDonell',
    'Steven Reiss': 'Steven P. Reiss',
    'T. Ellman': 'Thomas Ellman',
    'Thomas Dean': 'Thomas R. Dean',
    'Tiago Alves': 'Tiago L. Alves',
    'Tien Nguyen': 'Tien N. Nguyen',
    'Tien Nhut Nguyen': 'Tien N. Nguyen',
    'Tung Nguyen': 'Tung Thanh Nguyen',
    'Ulrich Nickel': 'Ulrich Nickel 0002',
    'Vikrant Kaulgud': 'Vikrant S. Kaulgud',
    'Vikrant Kaulgud':'Vikrant S. Kaulgud',
    'Vugranam Sreedhar': 'Vugranam C. Sreedhar',
    'W. K. Chan': 'Wing Kwong Chan',
    'William Sumner': 'William N. Sumner',
    'Ye Zhang': 'Ye Zhang 0002',
    'Yuichiro Nakagawa': 'Yuichiroh Nakagawa',
    'Zachary Fry': 'Zachary P. Fry',


}

