"""Copyright 2012-2013
Eindhoven University of Technology (Bogdan Vasilescu and Alexander Serebrenik) and
University of Mons (Tom Mens)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>."""

'''Additional lookup table for names, used for disambiguation'''

nameMap = {

    'A. Di Maio': 'Andrea Di Maio',
    'A. Fuggetta': 'Alfonso Fuggetta',
    'Aaron Larson': 'Aaron A. Larson',
    'Aaron Visaggio': 'Corrado Aaron Visaggio',
    'Adam Nasr': 'Khalid Adam Nasr',
    'Adam Porter': 'Adam A. Porter',
    'Aditya Mathur': 'Aditya P. Mathur',
    'Aditya Nori': 'Aditya V. Nori',
    'Ahmed Hassan': 'Ahmed E. Hassan',
    'Aiko Yamashita': 'Aiko Fallas Yamashita',
    'Akos Kiss 0001':'Akos Kiss',
    'Alan Brown': 'Alan W. Brown',
    'Alan Hu': 'Alan J. Hu',
    'Alan Whitehurst': 'R. Alan Whitehurst',
    'Alastair David Reid': 'Alastair D. Reid',
    'Alastair Reid': 'Alastair D. Reid',
    'Albert Zuendorf': 'Albert Zundorf',
    'Alex Borgida': 'Alexander Borgida',
    'Alex Kotov': 'Alexander Kotov',
    'Alex Orso': 'Alessandro Orso',
    'Alex Salcianu': 'Alexandru Salcianu',
    'Alex Telea': 'Alexandru Telea',
    'Alexander Kaiser 0001':'Alexander Kaiser',
    'Alexander Wolf': 'Alexander L. Wolf',
    'Alexandros Chatzigeorgiou': 'Alexander Chatzigeorgiou',
    'Alexandru C. Telea': 'Alexandru Telea',
    'Alexandru D. Salcianu': 'Alexandru Salcianu',
    'Alfred W. Strohmeier': 'Alfred Strohmeier',
    'Ali Razavi': 'Alireza Razavi',
    'Alistair Sutcliffe': 'Alistair G. Sutcliffe',
    'Amie Souter': 'Amie L. Souter',
    'Amit Paradkar': 'Amit M. Paradkar',
    'Amnon Eden': 'Amnon H. Eden',
    'Amy Murphy': 'Amy L. Murphy',
    'Ana Cavalli': 'Ana R. Cavalli',
    'Ana Moreno': 'Ana M. Moreno',
    'Anders L. B. Moller': 'Anders Moller',
    'Andrea Skarra': 'Andrea H. Skarra',
    'Andrew Bernat': 'Andrew R. Bernat',
    'Andrew Malton': 'Andrew J. Malton',
    'Andrew Symonds': 'Andrew J. Symonds',
    'Andrew Tolmach': 'Andrew P. Tolmach',
    'Andrey Terekhov': 'Andrey A. Terekhov',
    'Andy Meneely': 'Andrew Meneely',
    'Andy Schuerr': 'Andy Schurr',
    'Anh Nguyen': 'Hoan Anh Nguyen',
    'Anh Tuan Nguyen': 'Hoan Anh Nguyen',
    'Anh Tuan Nguyen':'Hoan Anh Nguyen',
    'Aniruddha Gokhale': 'Aniruddha S. Gokhale',
    'Annervaz K M':'K. M. Annervaz',
    'Annie Anton': 'Annie I. Anton',
    'Annie Ying': 'Annie T. T. Ying',
    'Anthony Hall': 'Anthony D. Hall',
    'Arie Van Deursen': 'Arie van Deursen',
    'Armando Haeberer': 'Armando Martin Haeberer',
    'Arosha Bandara': 'Arosha K. Bandara',
    'Arthur Reyes': 'Arthur Alexander Reyes',
    'Artur Garcez': 'Artur S. d\'Avila Garcez',
    'Arvind Krishna': 'Arvind S. Krishna',
    'Atanas (Nasko) Rountev': 'Atanas Rountev',
    'Atif Memon': 'Atif M. Memon',
    'Avinash Kak':'Avinash C. Kak',
    'Axel Van Lamsweerde': 'Axel van Lamsweerde',
    'B. Magnusson': 'Boris Magnusson',
    'B.M. Mainul Hossain': 'B. M. Mainul Hossain',
    'Barbara Kitchenham': 'Barbara A. Kitchenham',
    'Barbara Ryder': 'Barbara G. Ryder',
    'Barry Boehm': 'Barry W. Boehm',
    'Bart Jacobs 0002': 'Bart Jacobs',
    'Bart Jacobs 0002':'Bart Jacobs',
    'Barton Miller': 'Barton P. Miller',
    'Benjamin Zorn': 'Benjamin G. Zorn',
    'Bernd Fischer 0002':'Bernd Fischer',
    'Bernd Fischer 0002':'Bernd M. Fischer',
    'Bernd Fischer 0002':'Bernd M. Fischer',
    'Bernd Fischer': 'Bernd M. Fischer',
    'Bernd Freimut': 'Bernd G. Freimut',
    'Bernd Kraemer': 'Bernd J. Kramer',
    'Bernhard Aichernig': 'Bernhard K. Aichernig',
    'Betty Cheng': 'Betty H. C. Cheng',
    'Beverly Sanders': 'Beverly A. Sanders',
    'Bil Tzerpos':'Vassilios Tzerpos',
    'Bill Pugh':'William W. Pugh',
    'Bob Fuhrer':'Robert M. Fuhrer',
    'Bonnie John': 'Bonnie E. John',
    'Brad Martin': 'Bradley C. Martin',
    'Bradford Ulery': 'Bradford T. Ulery',
    'Bradley Schmerl': 'Bradley R. Schmerl',
    'Bran V. Selic': 'Bran Selic',
    'Brenda Baker': 'Brenda S. Baker',
    'Brian Bailey': 'Brian P. Bailey',
    'Brian Ellis': 'Brian J. Ellis',
    'Brian Malloy': 'Brian A. Malloy',
    'Brian Robinson': 'Brian P. Robinson',
    'Bruce Horowitz': 'Bruce M. Horowitz',
    'Bruce Krogh': 'Bruce H. Krogh',
    'C. Ghezzi':'Carlo Ghezzi',
    'C. Heitmeyer': 'Constance L. Heitmeyer',
    'Carl Worms': 'Carl F. Worms',
    'Carlo Alberto Furia': 'Carlo A. Furia',
    'Carlos J.P. Lucena': 'Carlos Jose Pereira de Lucena',
    'Carlos Lucena': 'Carlos Jose Pereira de Lucena',
    'Carolyn Seaman': 'Carolyn B. Seaman',
    'Catalin Roman': 'Gruia-Catalin Roman',
    'Cecilia Mary F. Rubira': 'Cecilia M. F. Rubira',
    'Cecilia Mary F. Rubira': 'Cecilia Mary Fischer Rubira',
    'Chanchal K. Roy': 'Chanchal Kumar Roy',
    'Chanchal Roy': 'Chanchal Kumar Roy',
    'Chandan Rupakheti': 'Chandan Raj Rupakheti',
    'Chao Liu 0001':'Chao Liu',
    'Charles Haley': 'Charles B. Haley',
    'Charles Knutson': 'Charles D. Knutson',
    'Chris Holland': 'Christopher P. Holland',
    'Chris Kemerer': 'Chris F. Kemerer',
    'Chris Marlin': 'Chris D. Marlin',
    'Chris Schofield': 'Christopher J. Schofield',
    'Chris van der Westhuizen': 'Christopher van der Westhuizen',
    'Christian Lange': 'Christian F. J. Lange',
    'Christina Cifuentes': 'Cristina Garcia Cifuentes',
    'Christoph Kessler': 'Christoph W. Kessler',
    'Christoph Schaefer': 'Christoph A. Schaefer',
    'Christopher Hughes': 'Christopher J. Hughes',
    'Christopher Lott': 'Christopher M. Lott',
    'Christopher Pidgeon': 'Christopher W. Pidgeon',
    'Clemens Szyperski': 'Clemens A. Szyperski',
    'Clement McGowan': 'Clement L. McGowan',
    'Colin Fidge': 'Colin J. Fidge',
    'Colin Mallows': 'Colin L. Mallows',
    'Colin Potts': 'Colin M. Potts',
    'Collin Mcmillan': 'Collin McMillan',
    'Connie Heitmeyer': 'Constance L. Heitmeyer',
    'Constance Heitmeyer': 'Constance L. Heitmeyer',
    'Corina Pasareanu': 'Corina S. Pasareanu',
    'Craig Wittenberg': 'Craig H. Wittenberg',
    'Cristina Cifuentes': 'Cristina Garcia Cifuentes',
    'Cristina Lopes': 'Cristina V. Lopes',
    'Cristina Lopes': 'Cristina Videira Lopes',
    'Cyrus Hall': 'Cyrus P. Hall',
    'D. Natale': 'Domenico Natale',
    'D. Rombach': 'H. Dieter Rombach',
    'D. Smith': 'D. W. Smith',
    'D.Yankelevich': 'Daniel Yankelevich',
    'Dag I.K. Sjoberg': 'Dag I. K. Sjoberg',
    'Dag Sjoberg': 'Dag I. K. Sjoberg',
    'Dallas Webster': 'Dallas E. Webster',
    'Dalton Dario Serey Guerrero': 'Dalton Serey Guerrero',
    'Dan Grossman': 'Daniel B. Grossman',
    'Daniel Berry': 'Daniel M. Berry',
    'Daniel German': 'Daniel M. German',
    'Daniel Grossman': 'Daniel B. Grossman',
    'Daniel Jackson': 'Daniel B. Jackson',
    'Daniel Laurence Moody': 'Daniel L. Moody',
    'Daniel LE METAYER': 'Daniel Le Metayer',
    'Daniel Moody': 'Daniel L. Moody',
    'Daniel Rosenkrantz': 'Daniel J. Rosenkrantz',
    'Daniel Waddington': 'Dan G. Waddington',
    'Daniel Yellin': 'Daniel M. Yellin',
    'Daniela S. Cruzes': 'Daniela Cruzes',
    'Danny Groenewegen': 'Danny M. Groenewegen',
    'Dany Yankelevich': 'Daniel Yankelevich',
    'Dave Binkley': 'David Binkley',
    'Dave Binkley': 'David M. Binkley',
    'Dave Card': 'David N. Card',
    'Dave King': 'Dave King 0002',
    'Dave Robson': 'David J. Robson',
    'Dave Wonnacott': 'David Wonnacott',
    'David Atkins': 'David L. Atkins',
    'David Barstow': 'David R. Barstow',
    'David Basin': 'David A. Basin',
    'David Binkley': 'David M. Binkley',
    'David Bustard': 'David W. Bustard',
    'David Eichmann': 'David A. Eichmann',
    'David Harris': 'David R. Harris',
    'David Huw Jones': 'David H. Jones',
    'David Jones': 'David H. Jones',
    'David Keyes': 'David S. Keyes',
    'David Mason': 'David V. Mason',
    'David Rosenblum': 'David S. Rosenblum',
    'David ROSENBLUM': 'David S. Rosenblum',
    'David Weiss': 'David M. Weiss',
    'David Wile': 'David S. Wile',
    'Dawson Engler': 'Dawson R. Engler',
    'Debra Richardson': 'Debra J. Richardson',
    'Dennis Smith': 'Dennis B. Smith',
    'Devaraj George': 'George Devaraj',
    'Dewayne Perry': 'Dewayne E. Perry',
    'Dieter Rombach': 'H. Dieter Rombach',
    'Dines Bjrner': 'Dines Bjorner',
    'Domenico de Natale': 'Domenico Natale',
    'Dominique MERY': 'Dominique Mery',
    'Don Batory': 'Don S. Batory',
    'Donald Pazel': 'Donald P. Pazel',
    'Doris Carver': 'Doris L. Carver',
    'Dorothy Setliff': 'Dorothy E. Setliff',
    'Doug Kimelman': 'Douglas N. Kimelman',
    'Douglas Schmidt': 'Douglas C. Schmidt',
    'Douglas White': 'Douglas A. White',
    'Duala-Ekoko': 'Ekwa Duala-Ekoko',
    'E. Hull': 'Emily Hull',
    'Earl Barr': 'Earl T. Barr',
    'Edwin Chan': 'Edwin C. Chan',
    'Edwin Westbrook': 'Edwin M. Westbrook',
    'Edy Liongosari': 'Edy S. Liongosari',
    'Elisa Baniassad': 'Elisa L. A. Baniassad',
    'Elizabeth Leonard': 'Elizabeth I. Leonard',
    'Elliot Chikofsky': 'Elliot J. Chikofsky',
    'Elmar Juergens':'Elmar Jurgens',
    'Emerson Murphy-Hill': 'Emerson R. Murphy-Hill',
    'Emery Berger': 'Emery D. Berger',
    'Eric Dashofy': 'Eric M. Dashofy',
    'Eric Eide': 'Eric Norman Eide',
    'Eric Schoen': 'Eric D. Schoen',
    'Eric Wong': 'W. Eric Wong',
    'Ettore M. Merlo': 'Ettore Merlo',
    'Ewan Tempero': 'Ewan D. Tempero',
    'F. De Paoli': 'Flavio De Paoli',
    'F. McGarry':'Frank E. McGarry',
    'F. Paulisch': 'Frances Paulisch',
    'F. van der Linden': 'Frank van der Linden',
    'Fadi Zaraket': 'Fadi A. Zaraket',
    'Fethi Rabhi': 'Fethi A. Rabhi',
    'Filipo Ricca': 'Filippo Ricca',
    'Francesco Sorrentino': 'Francesco Sorrentino 0002',
    'Frank Calliss': 'Frank W. Calliss',
    'Frank Shipman': 'Frank M. Shipman III',
    'Fred Schneider': 'Fred B. Schneider',
    'G. Leavens': 'Gary T. Leavens',
    'G. Renardel de Lavalette': 'Gerard R. Renardel de Lavalette',
    'Gail Kaiser': 'Gail E. Kaiser',
    'Gail Murphy': 'Gail C. Murphy',
    'Gang Huang': 'Gang Huang 0001',
    'Gary Anderson': 'Gary E. Anderson',
    'Gary Leavens': 'Gary T. Leavens',
    'Gary T. LEAVENS': 'Gary T. Leavens',
    'Geoff Clemm':'Geoffrey Clemm',
    'George Avrunin': 'George S. Avrunin',
    'George Baah': 'George K. Baah',
    'George Heineman': 'George T. Heineman',
    'George Stark': 'George E. Stark',
    'George Wilkie': 'F. George Wilkie',
    'Gerald Gannod': 'Gerald C. Gannod',
    'Gerard Holzmann': 'Gerard J. Holzmann',
    'Gerhard Fischer': 'Gerhard G. Fischer',
    'German Rivera': 'German M. Rivera',
    'German Sibay': 'German E. Sibay',
    'Ghizlane El Boussaidi': 'Ghizlane El-Boussaidi',
    'Giacomo Sechi': 'Giacomo R. Sechi',
    'Gina Venolia': 'Gina Danielle Venolia',
    'Giulio Antoniol': 'Giuliano Antoniol',
    'Giuseppe Antonio di Lucca': 'Giuseppe A. Di Lucca',
    'Giuseppe Di Lucca': 'Giuseppe A. Di Lucca',
    'Gordon Blair': 'Gordon S. Blair',
    'Gordon Novak': 'Gordon S. Novak',
    'Grace Lewis': 'Grace A. Lewis',
    'Gregory Gay': 'Gregory R. Gay',
    'Gregory Kapfhammer': 'Gregory M. Kapfhammer',
    'Gregory Wilson': 'Gregory V. Wilson',
    'Guillaume Brat': 'Guillaume P. Brat',
    'Gul Agha': 'Gul A. Agha',
    'Gunnar Bergersen': 'Gunnar R. Bergersen',
    'Guoqing Xu': 'Guoqing (Harry) Xu',
    'Gursimran Singh Walia': 'Gursimran S. Walia',
    'Gursimran Walia': 'Gursimran S. Walia',
    'H. Mossenbock': 'Hanspeter Mossenbock',
    'H. Muller': 'Hausi A. Muller',
    'H. Obbink': 'J. Henk Obbink',
    'H. Saiedian': 'Hossein Saiedian',
    'H. Toetenel': 'Hans Toetenel',
    'H.-Arno Jacobsen': 'Hans-Arno Jacobsen',
    'Hakam Alomari': 'Hakam W. Alomari',
    'Hannu-Matti Jaervinen': 'Hannu-Matti Jarvinen',
    'Hans Kohler': 'Hans J. Kohler',
    'Harald Gall': 'Harald C. Gall',
    'Haroon Babri': 'Haroon A. Babri',
    'Harry Sneed': 'Harry M. Sneed',
    'Harvey Siy': 'Harvey P. Siy',
    'Hausi Mueller': 'Hausi A. Muller',
    'Hausi Muller': 'Hausi A. Muller',
    'Heinz Schmidt': 'Heinz W. Schmidt',
    'Helen Edwards': 'Helen M. Edwards',
    'Helen Sharp': 'Helen C. Sharp',
    'Heng Lu 0001':'Heng Lu',
    'Herbert Prhofer': 'Herbert Prahofer',
    'Hernan Melgratti': 'Hernan C. Melgratti',
    'Hoan Nguyen': 'Hoan Anh Nguyen',
    'Holger Kienle': 'Holger M. Kienle',
    'Houari Sahraoui': 'Houari A. Sahraoui',
    'Howard Shrobe': 'Howard E. Shrobe',
    'Hsiang-Jui Kungs': 'Hsiang-Jui Kung',
    'Hsiao Ming Tsou': 'Hsiao-Ming Tsou',
    'Huzefa Kagdi': 'Huzefa H. Kagdi',
    'I. Sommerville': 'Ian Sommerville',
    'Ian Bull': 'R. Ian Bull',
    'Ian Peake': 'Ian D. Peake',
    'Iida Hajimu': 'Hajimu Iida',
    'Ingolf Kruger': 'Ingolf H. Kruger',
    'Ioannis Kotsiopoulos': 'Ioannis A. Kotsiopoulos',
    'Ira Baxter': 'Ira D. Baxter',
    'Ira Smith': 'Ira A. Smith',
    'Istvan Forgas': 'Istvan Forgacs',    
    'J. A. de La Puente': 'Juan Antonio de la Puente',
    'J. C. Derniame': 'Jean-Claude Derniame',
    'J. Cook': 'Jonathan E. Cook',
    'J. Gonzalez-Barahona':'Jesus M. Gonzalez-Barahona',
    'J. Kramer': 'Jeff Kramer',
    'J. Kuusela': 'Juha Kuusela',
    'J. Palsberg': 'Jens Palsberg',
    'J. Taramaa': 'Jorma Taramaa',
    'J. Verner':'June M. Verner',
    'J. Welsh': 'Jim Welsh',
    'Jack Wileden': 'Jack C. Wileden',
    'Jacky Keung': 'Jacky W. Keung',
    'Jafar Al-Kofahi': 'Jafar M. Al-Kofahi',
    'James Bowring': 'James F. Bowring',
    'James Browne': 'James C. Browne',
    'James Clause': 'James A. Clause',
    'James Corbett': 'James C. Corbett',
    'James Cordy': 'James R. Cordy',
    'James Cross II': 'James H. Cross II',
    'James Herbsleb': 'James D. Herbsleb',
    'James Jones': 'James A. Jones',
    'James Larus': 'James R. Larus',
    'James Law': 'James B. Law',
    'James Leathrum': 'James F. Leathrum',
    'James Neighbors': 'James M. Neighbors',
    'James Noble': 'James S. Noble',
    'James Purtilo': 'James M. Purtilo',
    'James Terwilliger': 'James F. Terwilliger',
    'Jamieson Cobleigh': 'Jamieson M. Cobleigh',
    'Jane Hayes':'Jane Huffman Hayes',
    'Janice Singer': 'Janice A. Singer',
    'Jason King': 'Jason S. King',
    'Jason Mansell': 'Jason Xabier Mansell',
    'Jean Claude Derniame': 'Jean-Claude Derniame',
    'Jean Marie Favre': 'Jean-Marie Favre',
    'Jeannette Wing': 'Jeannette M. Wing',
    'Jeff Magee': 'Jeffrey N. Magee',
    'Jeff N. Magee': 'Jeffrey N. Magee',
    'Jeffery Van Baalen': 'Jeffrey Van Baalen',
    'Jeffrey Foster': 'Jeffrey S. Foster',
    'Jelber Sayyad Shirabad': 'Jelber Sayyad-Shirabad',
    'Jenny Zou': 'Ying Zou',
    'Jens Jahnke': 'Jens H. Jahnke',
    'Jereme Haack': 'Jereme N. Haack',
    'Jeremy Archuleta': 'Jeremy S. Archuleta',
    'Jeremy Siek': 'Jeremy G. Siek',
    'Jesus Gonzalez-Barahona': 'Jesus M. Gonzalez-Barahona',
    'Jesus M. Gonzales-Barahona': 'Jesus M. Gonzalez-Barahona',
    'Jia-Su Sun': 'Jiasu Sun',
    'Jian Lv': 'Lv Jian',
    'Jiang Zheng 0001':'Jiang Zheng',
    'Jim Bieman': 'James M. Bieman',
    'Jim Cordy': 'James R. Cordy',
    'Jim Gish': 'James W. Gish',
    'Jim Ning': 'Jim Q. Ning',
    'Jim Qun Ning': 'Jim Q. Ning',
    'Jing Sun 0002':'Jing Sun',
    'Jo Atlee': 'Joanne M. Atlee',
    'Joanne Atlee': 'Joanne M. Atlee',
    'Joao Pedro Sousa': 'Joao P. Sousa',
    'Joao Sousa': 'Joao P. Sousa',
    'Jochen M. Kuester': 'Jochen M. Kuster',
    'John Chaves': 'John A. Chaves',
    'John Criswell': 'John R. Criswell',
    'John Edwards': 'John M. Edwards',
    'John Field': 'John P. Field',
    'John Gannon': 'John D. Gannon',
    'John Grundy': 'John C. Grundy',
    'John Hosking': 'John G. Hosking',
    'John Keane': 'John A. Keane',
    'John Knight': 'John C. Knight',
    'John McGregor': 'John D. McGregor',
    'John Powell': 'John D. Powell',
    'John Rushby': 'John M. Rushby',
    'John Walker': 'John J. Walker',
    'Jonathan Bowen': 'Jonathan P. Bowen',
    'Jonathan Cook': 'Jonathan E. Cook',
    'Jonathan Maletic': 'Jonathan I. Maletic',
    'Jonathan Moffett': 'Jonathan D. Moffett',
    'Jonathan Whittle': 'Jonathan P. Whittle',
    'Jon Whittle': 'Jonathan P. Whittle',
    'Jorge Figueiredo': 'Jorge C. A. de Figueiredo',
    'Jose Fiadeiro': 'Jose Luiz Fiadeiro',
    'Jose L Arciniegas': 'Jose L. Arciniegas',
    'Joseph Goguen': 'Joseph A. Goguen',
    'Joseph Horgan': 'Joseph R. Horgan',
    'Joseph Near': 'Joseph P. Near',
    'Joseph Robert Horgan': 'Joseph R. Horgan',
    'Juan Carlos Duenas': 'Juan C. Duenas',
    'Juan Carlos Granja Alvarez': 'Juan Carlos Granja-Alvarez',
    'Juan Fernandez Ramil': 'Juan Fernandez-Ramil',
    'Juan Ramil': 'Juan F. Ramil',
    'Juergen Dingel': 'Juergen DingelJuergen Dingel',
    'Julia Lawall': 'Julia L. Lawall',
    'Julio Cesar Leite': 'Julio Cesar Sampaio do Prado Leite',
    'Julio Cesar S. do Prado Leite':'Julio Cesar Sampaio do Prado Leite',
    'Jun Li 0008':'Jun Li',
    'Jun Sun 0001':'Jun Sun',
    'Jurgen Rilling': 'Juergen Rilling',
    'Jurgen Vinju': 'Jurgen J. Vinju',
    'Jyotirmoy Deshmukh': 'Jyotirmoy V. Deshmukh',
    'K. Koskimies': 'Kai Koskimies',
    'K. Nakakoji': 'Kumiyo Nakakoji',
    'Karen Huff': 'Karen E. Huff',
    'Kari Nies': 'Kari A. Nies',
    'Karl Lieberherr': 'Karl J. Lieberherr',
    'Kathy Davis': 'Kathi Hogshead Davis',
    'Keith Bennett': 'Keith H. Bennett',
    'Kenichi Matsumoto': 'Ken-ichi Matsumoto',
    'Kenichiro Matsumoto': 'Ken-ichi Matsumoto',
    'Kenneth Anderson': 'Kenneth M. Anderson',
    'Kenneth Frazier': 'Kenneth B. Frazier',
    'Kenneth Mark Anderson': 'Kenneth M. Anderson',
    'Kevin Conroy': 'Kevin M. Conroy',
    'Kevin Hoffman': 'Kevin J. Hoffman',
    'Kevin Schneider': 'Kevin A. Schneider',
    'Kevin Sullivan': 'Kevin J. Sullivan',
    'Klaus Hennig': 'Klaus Henning',
    'Kong Weiqiang': 'Weiqiang Kong',
    'Kostas Kontagiannis':'Kostas Kontogiannis',
    'Kris de Volder': 'Kris De Volder',
    'Krishna Mehra': 'Krishna K. Mehra',
    'Kurt Stirewalt': 'R. E. Kurt Stirewalt',
    'Kyle Canavera': 'Kyle R. Canavera',
    'L. Dillon':'Laura K. Dillon',
    'Lajos Jeno': 'Lajos Jeno Fulop',
    'Larry Markosian': 'Lawrence Markosian',
    'Laura Dillon': 'Laura K. Dillon',
    'Laurie DILLON': 'Laurie Dillon',
    'Laurie Williams': 'Laurie A. Williams',
    'Lawrence G. Votta Jr.': 'Lawrence G. Votta',
    'Lawrence Votta': 'Lawrence G. Votta',
    'Lee Osterweil': 'Leon J. Osterweil',
    'Lee White': 'Lee J. White',
    'Lei Wang 0018': 'Lei Wang',
    'Lei Wang 0018':'Lei Wang',
    'Lennart Kats': 'Lennart C. L. Kats',
    'Leopoldo Bertossi': 'Leopoldo E. Bertossi',
    'Les Gasser':'Leslie Gasser',
    'Letha Hughes Etzkorn': 'Letha H. Etzkorn',
    'Lewis Johnson': 'W. Lewis Johnson',
    'Li Zhang 0004':'Li Zhang',
    'Linda Northrop': 'Linda M. Northrop',
    'Linda Wills': 'Linda M. Wills',
    'Lingxiao JIANG': 'Lingxiao Jiang',
    'Lionel Briand': 'Lionel C. Briand',
    'Liwu Li 0001':'Liwu Li',
    'Loren Terveen': 'Loren G. Terveen',
    'Lori Pollock': 'Lori L. Pollock',
    'Lu Zhang 0023':'Lu Zhang',
    'Luay H. Tahat': 'Luay Ho Tahat',
    'Lucas Panjer': 'Lucas D. Panjer',
    'Luciano Da Fontoura Costa': 'Luciano da Fontoura Costa',
    'M. Dwyer': 'Matthew B. Dwyer',
    'M. Feather':'Martin S. Feather',
    'M. Glinz': 'Martin Glinz',
    'M. Harrold': 'Mary Jean Harrold',
    'M. Hinchey': 'Michael G. Hinchey',
    'M. Loewe':'Michael Lowe',
    'M. Mtihlhauser':'Max Muhlhauser',
    'M. Pezze': 'Mauro Pezze',
    'M. Saeki':'Motoshi Saeki',
    'M. Sitaraman': 'Murali Sitaraman',
    'M. Zelkowitz':'Marvin V. Zelkowitz',
    'Madhusudan Parthasarathy':'P. Madhusudan',
    'Magnus Larsson': 'Magnus E. Larsson',
    'Maja d\'Hondt': 'Maja D\'Hondt',
    'Malay Ganai': 'Malay K. Ganai',
    'Mamadou Diallo': 'Mamadou H. Diallo',
    'Manar Alalfi': 'Manar H. Alalfi',
    'Manny Lehman': 'Meir M. Lehman',
    'Manoel Mendonca': 'Manoel G. Mendonca',
    'Marc Kellner': 'Marc I. Kellner',
    'Marcela Fabiana Genero Bocco': 'Marcela Genero Bocco',
    'Marcelo Fabiun Frias': 'Marcelo F. Frias',
    'Marcelo Frias': 'Marcelo F. Frias',
    'Marco Tulio Valente': 'Marco Tulio de Oliveira Valente',
    'Margaret Burnett': 'Margaret M. Burnett',
    'Margaret Lyell': 'Margaret J. Lyell',
    'Margaret Smith': 'Margaret H. Smith',
    'Margaret-Anne Storey': 'Margaret-Anne D. Storey',
    'Mariano Moscato': 'Mariano M. Moscato',
    'Marie Vans': 'A. Marie Vans',
    'Mariella Tortorella': 'Maria Tortorella',
    'Mario Linares-Vasquez': 'Mario Linares Vasquez',
    'Mario Linares-Vasquez': 'Mario Linares Vasquez',
    'Mario Linares': 'Mario Linares Vasquez',
    'Marius Bogdan Spinu': 'Marius B. Spinu',
    'Mark Alan Jones': 'Mark A. Jones',
    'Mark Greenwood': 'R. Mark Greenwood',
    'Mark Jones': 'Mark A. Jones',
    'Mark Linton': 'Mark A. Linton',
    'Mark Van Den Brand': 'Mark G. J. van den Brand',
    'Marlon DUMAS': 'Marlon Dumas',
    'Marta Kwiatkowska': 'Marta Z. Kwiatkowska',
    'Martin GLINZ': 'Martin Glinz',
    'Martin Griss': 'Martin L. Griss',
    'Martin Grosse Rhode': 'Martin Grosse-Rhode',
    'Martin Robillard': 'Martin P. Robillard',
    'Martin Sheppard': 'Martin J. Shepperd',
    'Martin Shepperd': 'Martin J. Shepperd',
    'Martin Ward': 'Martin P. Ward',
    'Mary Fernandez': 'Mary F. Fernandez',
    'Mary Hall': 'Mary W. Hall',
    'Mary Shaw': 'Mary M. Shaw',
    'Massimiliano di Penta': 'Massimiliano Di Penta',
    'Mathew Flatt': 'Matthew Flatt',
    'Mats Heimdahl': 'Mats Per Erik Heimdahl',
    'Matt Dwyer': 'Matthew B. Dwyer',
    'Matt Dwyer':'Matthew B. Dwyer',
    'Matthew Dwyer': 'Matthew B. Dwyer',
    'Matthew Marcus': 'Matthew A. Marcus',
    'Matthias Wagner': 'Matthias Wagner 0001',
    'Md Kamal Hossen': 'Kamal Hossen',
    'Mehdi Harandi': 'Mehdi T. Harandi',
    'Mehmet Orgun': 'Mehmet A. Orgun',
    'Melissa Chase': 'Melissa P. Chase',
    'Meng Sun': 'Sun Meng',
    'Michael Blaha': 'Michael R. Blaha',
    'Michael Collard': 'Michael L. Collard',
    'Michael Cusumano': 'Michael A. Cusumano',
    'Michael Ernst': 'Michael D. Ernst',
    'Michael Godfrey': 'Michael W. Godfrey',
    'Michael Harrison': 'Michael D. Harrison',
    'Michael Houle': 'Michael E. Houle',
    'Michael Loewe': 'Michael Lowe',
    'Michael Lyu': 'Michael R. Lyu',
    'Michael Muller': 'Michael J. Muller',
    'Michael Olsem': 'Michael R. Olsem',
    'Michael Van De Vanter': 'Michael L. Van de Vanter',
    'Michael Whalen': 'Michael W. Whalen',
    'Michel Chaudron': 'Michel R. V. Chaudron',
    'Michelle Mills Strout': 'Michelle Strout',
    'Mike Godfrey': 'Michael W. Godfrey',
    'Mike Papazoglou': 'Mike P. Papazoglou',
    'Mike Schrank': 'Michael Schrank',
    'Mike W. Godfrey':'Michael W. Godfrey',
    'Mira Kajko-Mattson': 'Mira Kajko-Mattson',
    'Mira Kajko-Mattson': 'Mira Kajko-Mattsson',
    'Miriam Capretz': 'Miriam A. M. Capretz',
    'Mitch Lubars': 'Mitchell D. Lubars',
    'Mohammed El Ramly': 'Mohammad El-Ramly',
    'Monica Lam': 'Monica S. Lam',
    'Morven Gentleman': 'W. Morven Gentleman',
    'Muhammad Naeem 0002':'Muhammad Naeem',
    'Myra Cohen': 'Myra B. Cohen',
    'N. Leveson':'Nancy G. Leveson',
    'Nabor Mendonca': 'Nabor C. Mendonca',
    'Naftaly Minsky': 'Naftaly H. Minsky',
    'Nancy Day': 'Nancy A. Day',
    'Nancy Leveson': 'Nancy G. Leveson',
    'Narciso Marti Oliet': 'Narciso Marti-Oliet',
    'Naser Barghouti': 'Naser S. Barghouti',
    'Natalia Juristo': 'Natalia Juristo Juzgado',
    'Neil Maiden': 'Neil A. M. Maiden',
    'Nenad Medvidovich': 'Nenad Medvidovic',
    'Nicholas Chen': 'Nicholas Y. Chen',
    'Nicholas Kraft': 'Nicholas A. Kraft',
    'Nicolas Gold': 'Nicolas E. Gold',
    'Niels Veerman': 'Niels P. Veerman',
    'Nikolaj Bjoerner': 'Nikolaj Bjorner',
    'Norbert Fuchs': 'Norbert E. Fuchs',
    'Norman Schneidewind': 'Norman F. Schneidewind',
    'Ophelia Chesley': 'Ophelia C. Chesley',
    'Oscar NIERSTRASZ': 'Oscar Nierstrasz',
    'P. Botella': 'Pere Botella',
    'P. Devanbu':'Premkumar T. Devanbu',
    'P. Garg': 'Pankaj K. Garg',
    'P. Jalote':'Pankaj Jalote',
    'P. Kroha': 'Petr Kroha',
    'P. Zave': 'Pamela Zave',
    'Pamela ZAVE': 'Pamela Zave',
    'Pankaj Garg': 'Pankaj K. Garg',
    'Panos Linos': 'Panagiotis K. Linos',
    'Parthasarathy Madhusudan': 'P. Madhusudan',
    'Pasi Kavaja': 'Pasi Kuvaja',
    'Patricia Oberndorf': 'Patricia A. Oberndorf',
    'Patrick Maeder':'Patrick Mader',
    'Paul A Bailes': 'Paul A. Bailes',
    'Paul Bailes': 'Paul A. Bailes',
    'Paul Bailor': 'Paul D. Bailor',
    'Paul Bannerman': 'Paul L. Bannerman',
    'Paul Clements': 'Paul C. Clements',
    'Paul Dan Marinescu': 'Paul Marinescu',
    'Paul Gruehnbacher': 'Paul Grunbacher',
    'Paul Gruenbacher': 'Paul Grunbacher',
    'Paul Layzell': 'Paul J. Layzell',
    'Paul Oman': 'Paul W. Oman',
    'Paul Sorenson': 'Paul G. Sorenson',
    'Paul Steckler': 'Paul A. Steckler',
    'Paul Strooper': 'Paul A. Strooper',
    'Paulo Masiero': 'Paulo Masiero Masiero',
    'Paulo R. F. Cunha': 'Paulo Cunha',
    'Pedro D\'Argenio': 'Pedro R. D\'Argenio',
    'Pedro Dias Guerreiro': 'Pedro Guerreiro',
    'Peri Tarr': 'Peri L. Tarr',
    'Peter Feiler': 'Peter H. Feiler',
    'Peter Mehlitz': 'Peter C. Mehlitz',
    'Peter Mosses': 'Peter D. Mosses',
    'Peter Olveczky': 'Peter Csaba Olveczky',
    'Peter Rigby': 'Peter C. Rigby',
    'Peter Rotella':'Pete Rotella',
    'Philip Fong': 'Philip W. L. Fong',
    'Phyllis Frankl': 'Phyllis G. Frankl',
    'Pinto Carlos': 'Carlos Pinto',
    'Prasanta Bose': 'Prasanta K. Bose',
    'Prem Devanbu': 'Premkumar T. Devanbu',
    'Premkumar Devanbu': 'Premkumar T. Devanbu',
    'Qin Ma 0002':'Qin Ma',
    'R. Balzer':'Robert M. Balzer',
    'R. Conradi': 'Reidar Conradi',
    'R. Jeffery':'D. Ross Jeffery',
    'R. Kemmerer': 'Richard A. Kemmerer',
    'R. Klosch': 'Rene Klosch',
    'Rachel Bellamy': 'Rachel K. E. Bellamy',
    'Raimund Feldmann': 'Raimund L. Feldmann',
    'Raj Sood': 'H. Raj Sood',
    'Rajseh Vasa': 'Rajesh Vasa',
    'Ralf Kollman': 'Ralf Kollmann',
    'Ralf Laemmel': 'Ralf Lammel',
    'Ralf Reussner': 'Ralf H. Reussner',
    'Ralph Johnson': 'Ralph E. Johnson',
    'Ralph Lammel':'Ralf Lammel',
    'Randy Howard Katz': 'Randy H. Katz',
    'Randy Katz': 'Randy H. Katz',
    'Raul Santelices': 'Raul A. Santelices',
    'Ravi Sandhu': 'Ravi S. Sandhu',
    'Reiner Dumke': 'Reiner R. Dumke',
    'REmy Sanlaville': 'Remy Sanlaville',
    'Rene Kloesch': 'Rene Klosch',
    'Rene Krikhaar': 'Rene L. Krikhaar',
    'Rene R. Kloesch': 'Rene Klosch',
    'Ric Holt': 'Richard C. Holt',
    'Richard Chang': 'Richard M. Chang',
    'Richard Hall': 'Richard S. Hall',
    'Richard Holt': 'Richard C. Holt',
    'Richard Paige': 'Richard F. Paige',
    'Richard Piazza': 'Richard L. Piazza',
    'Richard Taylor': 'Richard N. Taylor',
    'Rob Hierons': 'Robert M. Hierons',
    'Rob Miller 0003':'Rob Miller',
    'Rob Rist': 'Robert S. Rist',
    'Robert Arnold': 'Robert S. Arnold',
    'Robert Bowdidge': 'Robert W. Bowdidge',
    'Robert Filman': 'Robert E. Filman',
    'Robert France': 'Robert B. France',
    'Robert Fuhrer': 'Robert M. Fuhrer',
    'Robert Griffiths': 'Robert P. Griffiths',
    'Robert Hierons': 'Robert M. Hierons',
    'Robert Mays': 'Robert G. Mays',
    'Robert Merkel': 'Robert G. Merkel',
    'Robert Walker': 'Robert J. Walker',
    'Roberto A. Bittencourt': 'Roberto Almeida Bittencourt',
    'Roberto Lopez-Herrejon': 'Roberto E. Lopez-Herrejon',
    'Roberto Silva Filho': 'Roberto Silveira Silva Filho',
    'Robyn Lutz': 'Robyn R. Lutz',
    'Roger Khazan': 'Roger I. Khazan',
    'Roland Mittermeir': 'Roland T. Mittermeir',
    'Ross Jeffery': 'D. Ross Jeffery',
    'Ruth BREU': 'Ruth Breu',
    'S. C. Cheung': 'Shing-Chi Cheung',
    'S. D. Swierstra': 'S. Doaitse Swierstra',
    'S. Feldman': 'Stuart I. Feldman',
    'S. Fickas':'Stephen Fickas',
    'S. Jerome Carriere': 'S. Jeromy Carriere',
    'S.C. Cheung': 'Shing-Chi Cheung',
    'Saleh Alnaeli': 'Saleh M. Alnaeli',
    'Sales Pinto': 'Leandro Sales Pinto',
    'Sandeep Shukla': 'Sandeep K. Shukla',
    'Saumya Debray': 'Saumya K. Debray',
    'Scanniello Giuseppe': 'Giuseppe Scanniello',
    'Scott Ankrum': 'T. Scott Ankrum',
    'Scott Fahlman': 'Scott E. Fahlman',
    'Scott Fleming': 'Scott D. Fleming',
    'Scott Tilley': 'Scott R. Tilley',
    'Sean Falconer': 'Sean M. Falconer',
    'Sebastian Elbaum': 'Sebastian G. Elbaum',
    'Shari Lawrence Ptleeger':'Shari Lawrence Pfleeger',
    'Shauvik Roy': 'Shauvik Roy Choudhary',
    'Shawn Bohner': 'Shawn A. Bohner',
    'Shawn Butler': 'Shawn A. Butler',
    'Siau Cheng Khoo': 'Siau-Cheng Khoo',
    'Simon Holland': 'Simon T. Holland',
    'Simon Kaplan': 'Simon M. Kaplan',
    'Simon Peyton Jones': 'Simon L. Peyton Jones',
    'Sol Greenspan': 'Sol J. Greenspan',
    'Sriram Rajamani': 'Sriram K. Rajamani',
    'Stan Zdonik': 'Stanley B. Zdonik',
    'Stephen Blackburn': 'Stephen M. Blackburn',
    'Stephen Cook 0002':'Stephen Cook',
    'Stephen Fink': 'Stephen J. Fink',
    'Stephen Foster': 'Stephen R. Foster',
    'Stephen MacDonell': 'Stephen G. MacDonell',
    'Stephen Schach': 'Stephen R. Schach',
    'Stephen Siegel': 'Stephen F. Siegel',
    'Steve Easterbrook': 'Steve M. Easterbrook',
    'Steve Fickas': 'Stephen Fickas',
    'Steve MacDonell': 'Steven G. MacDonell',
    'Steve Reiss': 'Steven P. Reiss',
    'Steve S. Yau': 'Stephen S. Yau',
    'Steven Brown': 'Steven W. Brown',
    'Steven Easterbrook': 'Steve M. Easterbrook',
    'Steven Reiss': 'Steven P. Reiss',
    'Steven Woods': 'Steven G. Woods',
    'Stuart Faulk': 'Stuart R. Faulk',
    'Stuart Kent': 'Stuart T. Kent',
    'Suraj Kothari': 'Suraj C. Kothari',
    'Susan Gerhart': 'Susan L. Gerhart',
    'Susan Graham': 'Susan L. Graham',
    'Sushil Bajracharya': 'Sushil Krishna Bajracharya',
    'Swee-Cheang Lim': 'Lim Swee Cheang',
    'T. Ellman': 'Thomas Ellman',
    'T. Maibaum':'Thomas Stephen Edward Maibaum',
    'T. Tamai':'Tetsuo Tamai',
    'T.H. Ng': 'T. H. Ng',
    'Taghi Khoshgoftaar': 'Taghi M. Khoshgoftaar',
    'Ted Biggerstaff': 'Ted J. Biggerstaff',
    'Teresa Baldassarre': 'Maria Teresa Baldassarre',
    'Tereza Kirner': 'Tereza G. Kirner',
    'Thanh Binh Nguyen 0002':'Nguyen Thanh Binh',
    'ThanhVu Nguyen': 'ThanhVu H. Nguyen',
    'Theo d\'Hondt': 'Theo D\'Hondt',
    'Thiago Bartolomei': 'Thiago T. Bartolomei',
    'Thomas Alspaugh': 'Thomas A. Alspaugh',
    'Thomas Ball': 'Thomas A. Ball',
    'Thomas Dean': 'Thomas R. Dean',
    'Thomas Dean': 'Thomas Roy Dean',
    'Thomas Gross': 'Thomas R. Gross',
    'Thomas J. McCabe Sr.': 'Thomas J. McCabe',
    'Thomas LaToza': 'Thomas D. LaToza',
    'Thomas Marlowe': 'Thomas J. Marlowe',
    'Thomas Ostrand': 'Thomas J. Ostrand',
    'Thuan Pham': 'Thuan Q. Pham',
    'Tiago Alves': 'Tiago L. Alves',
    'Tien Nguyen': 'Tien N. Nguyen',
    'Tien Nhut Nguyen': 'Tien N. Nguyen',
    'Tijs van Der Storm': 'Tijs van der Storm',
    'Tilmann Bruckhaus': 'Tilmann F. W. Bruckhaus',
    'Tim Leek': 'Timothy R. Leek',
    'Tim Lethbridge':'Timothy C. Lethbridge',
    'Timothy Lethbridge': 'Timothy C. Lethbridge',
    'Timothy Wright': 'Timothy N. Wright',
    'Tobias Roetschke': 'Tobias Rotschke',
    'Todd Millstein': 'Todd D. Millstein',
    'Todd Schiller': 'Todd W. Schiller',
    'Todd Veldhuizen': 'Todd L. Veldhuizen',
    'Tom Ball': 'Thomas A. Ball',
    'Tom Ellman': 'Thomas Ellman',
    'Tom Reps': 'Thomas W. Reps',
    'Tom Zimmermann': 'Thomas Zimmermann',
    'Tooru Takeshita': 'Toru Takeshita',
    'Torben Mogensen': 'Torben AE. Mogensen',
    'Toshiro Kamiya':'Toshihiro Kamiya',
    'Tung Nguyen': 'Tung T. Nguyen',
    'Tung Nguyen': 'Tung Thanh Nguyen',
    'Ugo Buy': 'Ugo A. Buy',
    'Ugo De Carlini': 'Ugo de Carlini',
    'Ulrich Nickel 0002':'Ulrich Nickel',
    'Ulrich Nickel 0002':'Ulrich Nickel',
    'Umut Acar': 'Umut A. Acar',
    'V. Shen': 'V. Y. Shen',
    'Vasu Alagar': 'Vasu S. Alagar',
    'Victor Basili': 'Victor R. Basili',
    'Victor Braberman': 'Victor A. Braberman',
    'Victor Kasyanov': 'Victor N. Kasyanov',
    'Vikrant Kaulgud': 'Vikrant S. Kaulgud',
    'Vikrant Kaulgud':'Vikrant S. Kaulgud',
    'Vu Ha': 'Vu A. Ha',
    'Vugranam Sreedhar': 'Vugranam C. Sreedhar',
    'W. Agresti': 'William W. Agresti',
    'W. Bischofberger': 'Walter R. Bischofberger',
    'W. Emmerich': 'Wolfgang Emmerich',
    'W. Glatthaar': 'Wolfgang Glatthaar',
    'W. Griswold': 'William G. Griswold',
    'W. K. Chan': 'Wing Kwong Chan',
    'W. Melo': 'Walcelio L. Melo',
    'W. Schaefer':'Wilhelm Schafer',
    'W. Turski':'Wladyslaw M. Turski',
    'W.J. Toetenel': 'Hans Toetenel',
    'W.K. Chan': 'Wing Kwong Chan',
    'Walcelio Melo': 'Walcelio L. Melo',
    'Walter Scacchi': 'Walt Scacchi',
    'Walter Tichy': 'Walter F. Tichy',
    'Wang Yi 0001':'Wang Yi',
    'Wilhelm Schaefer': 'Wilhelm Schafer',
    'Will Dietz': 'William Dietz',
    'Will Tracz': 'William J. Tracz',
    'Willem C. Visser': 'Willem Visser',
    'William Agresti': 'William W. Agresti',
    'William Cook': 'William R. Cook',
    'William Griswold': 'William G. Griswold',
    'William Halfond': 'William G. J. Halfond',
    'William Marsh': 'William E. Marsh',
    'William Pugh':'William W. Pugh',
    'William Robinson': 'William N. Robinson',
    'William Scherlis': 'William L. Scherlis',
    'William Sumner': 'William N. Sumner',
    'Xiangyu Zhang': 'Xiangyun Zhang',
    'Xiaoqing (Frank) Liu': 'Xiaoqing Liu',
    'Xiaoqing Frank Liu': 'Xiaoqing Liu',
    'Xiaoyin Wang': 'Xiaoying Wang',
    'Xin (Shin) Zhang': 'Xin Zhang',
    'Y.T. Yu': 'Y. T. Yu',
    'Yanhong Annie Liu': 'Yanhong A. Liu',
    'Yannis Kanellopoulos': 'Yiannis Kanellopoulos',
    'Ye Zhang 0002':'Ye Zhang',
    'Yiannis Vassiliou': 'Yannis Vassiliou',
    'Yih-Farn Robin Chen': 'Yih-Farn Chen',
    'Ying (Jenny) Zou': 'Ying Zou',
    'Yong-Min Kim': 'Yong-Mi Kim',
    'Yuichiro Nakagawa': 'Yuichiroh Nakagawa',
    'Zachary Fry': 'Zachary P. Fry',    
    'Dean Hendrix': 'T. Dean Hendrix',
    'Peter Aiken': 'Peter H. Aiken',
    'Peter Selfridge': 'Peter G. Selfridge',
    'Marlon Vieira':'Marlon E. R. Vieira',
    'Ingolf Krueger':'Ingolf H. Kruger',
    'Clinton Jeffery':'Clinton L. Jeffery',
    'Rodrigo Vivanco':'Rodrigo A. Vivanco',
    'Oscar S\'nchez Ramon':'Oscar Sanchez Ramon',
    'Jorn Guy Suss':'Jorn Guy Sus',
    'Kevin Gary':'Kevin A. Gary',
    'Carsten Goerg':'Carsten Gorg',
    'Michael Lowry':'Michael R. Lowry',
    'Mark Wilson':'Mark L. Wilson',
    'Bashar Nllseibeh':'Bashar Nuseibeh',
    'I. Thomas':'Ian Thomas',
    'Tony Cahill':'Anthony Cahill',
    'R. Jacquart':'Rene Jacquart',
    'J. McHugh':'John McHugh',
    

    
}


'''Check for transitivity'''
if __name__=="__main__":
    l = []
    for key,val in nameMap.items():
        l.append((key,val))
    import itertools
    for a,b in itertools.combinations(sorted(l),2):
        if a[0]==b[1] or a[1]==b[0]:
            print a,b


    
    